# Generated by Django 4.1.5 on 2023-01-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_comment_publicated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
